-- Tabela: contraventor
CREATE TABLE contraventor (
    id_cont BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cpf_cont VARCHAR(255) NOT NULL,
    login VARCHAR(255) NOT NULL,
    nome_cont VARCHAR(255),
    password VARCHAR(255) NOT NULL,
    tipo_cont VARCHAR(255),
    CONSTRAINT uk_cpf_cont UNIQUE (cpf_cont),
    CONSTRAINT uk_login UNIQUE (login),
    CONSTRAINT uk_password UNIQUE (password)
);

-- Tabela: cliente
CREATE TABLE cliente (
    id_cli BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bairro_cli VARCHAR(255),
    cep_cli VARCHAR(255),
    cidade_cli VARCHAR(255),
    cpf_cli VARCHAR(255) NOT NULL,
    estado_cli VARCHAR(255),
    logradouro_cli VARCHAR(255),
    nome_cli VARCHAR(255),
    numero_cli INTEGER NOT NULL,
    rg_cli VARCHAR(255) NOT NULL,
    CONSTRAINT uk_cpf_cli UNIQUE (cpf_cli),
    CONSTRAINT uk_rg_cli UNIQUE (rg_cli)
);

-- Tabela: bicho
CREATE TABLE bicho (
    id_bicho BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome_bicho VARCHAR(255),
    tipo_aposta VARCHAR(255),
    id_cont BIGINT,
    id_cli BIGINT,
    val_aposta DOUBLE PRECISION,
    banca_aposta VARCHAR(255),
    forma_pagamento VARCHAR(255),
    data_aposta TIMESTAMP(6),
    CONSTRAINT contraventor_fkey FOREIGN KEY (id_cont) REFERENCES contraventor(id_cont),
    CONSTRAINT cliente_fkey FOREIGN KEY (id_cli) REFERENCES cliente(id_cli)
);

-- Índices automáticos criados nas colunas PRIMARY KEY e UNIQUE são adicionados conforme descrito.
